apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: credit-card-v1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: credit-card
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 20